name: Tech Mancing
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.6
  get: ^4.6.5
  geolocator: ^10.0.0
  baseflow_plugin_template: ^2.1.2
  simple_ripple_animation: ^0.0.7
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  permission_handler: ^11.0.0
  flutter_compass: ^0.8.0
  flutter_secure_storage: ^9.0.0
  multi_select_flutter: ^4.1.3
  file_picker: ^6.0.0
  fluttertoast: ^8.0.9
  intl: ^0.17.0
  flutter_map_tile_caching: ^9.0.0-dev.3
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
